name: Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        
    - run: ls -la
    - run: mkdir json
    - run: cp ./html/latest.html ./html/latest/index.html
    - name: Get laws.json
      run: curl https://tcfshsu.github.io/law/json/laws.json > ./json/laws.json
    - name: Get cases.json
      run: curl https://tcfshsu.github.io/law/json/cases.json > ./json/cases.json
    - name: Get latest.json
      run: curl https://tcfshsu.github.io/law/json/latest.json > ./json/latest.json
    - name: Get parties.json
      run: curl https://tcfshsu.github.io/law/json/parties.json > ./json/parties.json
    - name: Generate files
      run: dotnet run
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4